#+TITLE: OhMyECH - ECH Indicator
#+AUTHOR: Justin Andreas Lacoste
#+EMAIL: me@justin.cx

* Introduction

This extension adds an icon to Firefox's address bar which indicates whether this page used [[https://en.wikipedia.org/wiki/Server_Name_Indication#Encrypted_Client_Hello][Encrypted-Client-Hello (ECH)]]
or not.

ECH is a much needed privacy extension that landed in Firefox 118. Before the days of ECH, any middleman (e.g. your ISP)
between your device and the server you're talking to was able to sniff out the domain of the page you're visiting ([[https://en.wikipedia.org/wiki/Server_Name_Indication][using
the **SNI** of the Client-Hello]]).

I believe that an indication for ECH is as important as one for HTTP(S), thus this extension.

* Usage

After installing, whenever you navigate to a new page, on the right side of your address bar should appear a lock icon.
To properly communicate how ECH was used, OhMyECH may display four different lock icons:

| Colour | Meaning                                                                             |
|--------+-------------------------------------------------------------------------------------|
| Red    | At no point in time was ECH used within this tab.                                   |
| Green  | Every request originating from this tab used ECH (Best-case).                       |
| Blue   | The initial page load (the first request) used ECH, but subsequent fetches did not. |
| Orange | The initial page load did not use ECH, but a subsequent fetch did.                  |

During the lifetime of the tab, the lock may change colour.

The state of the OhMyECH lock is constrained on a tab-per-tab basis, any request originating from a tab is used in
determining the tabs ECH state, this includes AJAX fetches, images, scripts, etc. These checks also work cross-site,
meaning that if ~example.com~ were to load something from ~cdn.example.com~, it would still affect the ECH state.

* Screenshots

#+HTML: <img src="https://github.com/27justin/ohmyech/assets/72092018/ba6abc9b-e2ed-48b3-a799-0701031640b9" title="Active" />
#+HTML: <img src="https://github.com/27justin/ohmyech/assets/72092018/db794212-2c8d-4dea-ad61-128a464560e0" title="Inactive" />
#+HTML: <img src="https://github.com/27justin/ohmyech/assets/72092018/8710c455-9184-44a7-aed0-cabc13f7b7bb" title="Partial" />
#+HTML: <img src="https://github.com/27justin/ohmyech/assets/72092018/9dd384c6-5fdc-4b02-ada6-16d2c18972b0" title="Initial" />

* Tests

Test whether the Extension, and in extension ECH works for your device/browser:

+ [[https://defo.ie/ech-check.php]]
+ [[https://encryptedsni.com/cdn-cgi/trace][https://encryptedsni.com/cdn-cgi/trace]]

* Credits
+ [[https://github.com/lucide-icons/lucide][Lucide]] for the Lock SVGs
